project:
  type: website
  output-dir: docs

website:
  title: "Saralyst Consult"
  logo: images/calculations.jpg
  navbar:
    left:
      - href: index.qmd
      - about.qmd

format:
  html:
    theme: simple
    css: styles.css
    toc: true

editor: visual

